import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Button from "@/shared/Button/Button";
import Link from "next/link";


export default function Home() {
  return (
    <>
      <Head>
        <title>Локальный блок</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} `}>
        <div className={styles.description}>
        </div>

        <div className={styles.center}>
          <img
            className={styles.logo}
            src="/logo512.png"
            alt="Logo"
          />
          <h1>Локальный блок</h1>
          <div className={styles.buttons}>
            <Link href="/auth/login"><Button>Войти</Button></Link>
            <Link href="/auth/registration"><Button variant="outlined">Регистрация</Button></Link>
          </div>
        </div>

        <div className={styles.grid}>
        </div>
      </main>
    </>
  );
}
